# Generated by Django 4.2.7 on 2023-11-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_userlunch_alter_lunchposition_options_userlunchitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentManage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
